// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PassportCodeChallenge.Data;

namespace PassportCodeChallenge.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181218071312_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("PassportCodeChallenge.Models.Factory", b =>
                {
                    b.Property<int>("FactoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("FactoryId");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("PassportCodeChallenge.Models.FactoryChild", b =>
                {
                    b.Property<int>("FactoryChildId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FactoryId");

                    b.Property<int>("Value");

                    b.HasKey("FactoryChildId");

                    b.HasIndex("FactoryId");

                    b.ToTable("FactoryChild");
                });

            modelBuilder.Entity("PassportCodeChallenge.Models.FactoryChild", b =>
                {
                    b.HasOne("PassportCodeChallenge.Models.Factory")
                        .WithMany("Children")
                        .HasForeignKey("FactoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
